### ISSUE TITLE
gi.require_version("Wnck", "3.0")

### ISSUE THREAD

**Issue by rodneylg** [deter0/xborder#69]
I'm a noob, so I don't know what any of this means.  I'm trying to install this on Xubuntu 22.04

`Traceback (most recent call last):
  File "/home/[home]/SoftwareBuilds/xborder/./xborders", line 16, in <module>
    gi.require_version("Wnck", "3.0")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Wnck not available
`

**Comment by rodneylg** [comment]
Fixed it with this command:

`sudo apt install python3-gi gir1.2-wnck-3.0`
